apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-sbom-test-gitops
  description: This is GitOps manifest for go-sbom-test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=go-sbom-test
    backstage.io/kubernetes-id: go-sbom-test 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: lucarval-rhtap/go-sbom-test-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: lucarval-rhtap.go-sbom-test-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-sbom-test
